{-# OPTIONS -fglasgow-exts #-}

module OpenAFP.Prelude.Lookups where
import OpenAFP.Types
import OpenAFP.Records
import OpenAFP.Internals
import OpenAFP.Prelude.Instances

descLookup :: ChunkType -> String
descLookup = lookupWithDefaultFM descMap "(Unknown)" . show

descMap :: FiniteMap String String
descMap = listToFM [
    (show $ typeOf _MCF_T, "MCF Triplets"),
    (show $ typeOf _CPI, "Code Page Index"),
    (show $ typeOf _FNI, "Font Index"),
    (show $ typeOf _CFI, "Coded Font Index"),
    (show $ typeOf _MFC, "Medium Finishing Control"),
    (show $ typeOf _TLE, "Tag Logical Element"),
    (show $ typeOf _MCC, "Medium Copy Count"),
    (show $ typeOf _FNM, "Font Patterns Map"),
    (show $ typeOf _OBD, "Object Area Descriptor"),
    (show $ typeOf _IID, "IM Image Input Descriptor (C)"),
    (show $ typeOf _CPD, "Code Page Descriptor"),
    (show $ typeOf _MDD, "Medium Descriptor"),
    (show $ typeOf _FND, "Font Descriptor"),
    (show $ typeOf _CDD, "Container Data Descriptor"),
    (show $ typeOf _PTD1, "Presentation Text Descriptor Format-1 (C)"),
    (show $ typeOf _PGD, "Page Descriptor"),
    (show $ typeOf _GDD, "Graphics Data Descriptor"),
    (show $ typeOf _FGD, "Form Environment Group Descriptor (O)"),
    (show $ typeOf _DXD, "Data Map Transmission Subcase Descriptor"),
    (show $ typeOf _LND, "Line Descriptor"),
    (show $ typeOf _BDD, "Bar Code Data Descriptor"),
    (show $ typeOf _IDD, "Image Data Descriptor"),
    (show $ typeOf _IOC, "IM Image Output Control (C)"),
    (show $ typeOf _CPC, "Code Page Control"),
    (show $ typeOf _MMC, "Medium Modification Control"),
    (show $ typeOf _FNC, "Font Control"),
    (show $ typeOf _CFC, "Coded Font Control"),
    (show $ typeOf _CTC, "Composed Text Control (O)"),
    (show $ typeOf _PMC, "Page Modification Control"),
    (show $ typeOf _BPS, "Begin Page Segment"),
    (show $ typeOf _BCA, "Begin Color Attribute Table"),
    (show $ typeOf _BII, "Begin IM Image (C)"),
    (show $ typeOf _BCP, "Begin Code Page"),
    (show $ typeOf _BFN, "Begin Font"),
    (show $ typeOf _BCF, "Begin Coded Font"),
    (show $ typeOf _BOC, "Begin Object Container"),
    (show $ typeOf _BPT, "Begin Presentation Text Object"),
    (show $ typeOf _BDI, "Begin Document Index"),
    (show $ typeOf _BDT, "Begin Document"),
    (show $ typeOf _BNG, "Begin Named Page Group"),
    (show $ typeOf _BPG, "Begin Page"),
    (show $ typeOf _BGR, "Begin Graphics Object"),
    (show $ typeOf _BDG, "Begin Document Environment Group"),
    (show $ typeOf _BFG, "Begin Form Environment Group (O)"),
    (show $ typeOf _BRG, "Begin Resource Group"),
    (show $ typeOf _BOG, "Begin Object Environment Group"),
    (show $ typeOf _BAG, "Begin Active Environment Group"),
    (show $ typeOf _BDM, "Begin Data Map"),
    (show $ typeOf _BPM, "Begin Page Map"),
    (show $ typeOf _BMM, "Begin Medium Map"),
    (show $ typeOf _BFM, "Begin Form Map"),
    (show $ typeOf _BR, "Begin Resource (R)"),
    (show $ typeOf _BSG, "Begin Resource Environment Group"),
    (show $ typeOf _BMO, "Begin Overlay"),
    (show $ typeOf _BDX, "Begin Data Map Transmission Subcase"),
    (show $ typeOf _BBC, "Begin Bar Code Object"),
    (show $ typeOf _BIM, "Begin Image Object"),
    (show $ typeOf _EPS, "End Page Segment"),
    (show $ typeOf _ECA, "End Color Attribute Table"),
    (show $ typeOf _EII, "End IM Image (C)"),
    (show $ typeOf _ECP, "End Code Page"),
    (show $ typeOf _EFN, "End Font"),
    (show $ typeOf _ECF, "End Coded Font"),
    (show $ typeOf _EOC, "End Object Container"),
    (show $ typeOf _EPT, "End Presentation Text Object"),
    (show $ typeOf _EDI, "End Document Index"),
    (show $ typeOf _EDT, "End Document"),
    (show $ typeOf _ENG, "End Named Page Group"),
    (show $ typeOf _EPG, "End Page"),
    (show $ typeOf _EGR, "End Graphics Object"),
    (show $ typeOf _EDG, "End Document Environment Group"),
    (show $ typeOf _EFG, "End Form Environment Group (O)"),
    (show $ typeOf _ERG, "End Resource Group"),
    (show $ typeOf _EOG, "End Object Environment Group"),
    (show $ typeOf _EAG, "End Active Environment Group"),
    (show $ typeOf _EDM, "End Data Map"),
    (show $ typeOf _EPM, "End Page Map"),
    (show $ typeOf _EMM, "End Medium Map"),
    (show $ typeOf _EFM, "End Form Map"),
    (show $ typeOf _ER, "End Resource (R)"),
    (show $ typeOf _ESG, "End Resource Environment Group"),
    (show $ typeOf _EMO, "End Overlay"),
    (show $ typeOf _EDX, "End Data Map Transmission Subcase"),
    (show $ typeOf _EBC, "End Bar Code Object"),
    (show $ typeOf _EIM, "End Image Object"),
    (show $ typeOf _LNC, "Line Descriptor Count"),
    (show $ typeOf _MCA, "Map Color Attribute Table"),
    (show $ typeOf _MMT, "Map Media Type"),
    (show $ typeOf _FNN, "Font Names (Outline Fonts Only)"),
    (show $ typeOf _MCF, "Map Coded Font"),
    (show $ typeOf _MCD, "Map Container Data"),
    (show $ typeOf _MPG, "Map Page"),
    (show $ typeOf _MGO, "Map Graphics Object"),
    (show $ typeOf _MDR, "Map Data Resource"),
    (show $ typeOf _IMM, "Invoke Medium Map"),
    (show $ typeOf _MPO, "Map Page Overlay"),
    (show $ typeOf _MSU, "Map Suppression"),
    (show $ typeOf _MBC, "Map Bar Code Object"),
    (show $ typeOf _MIO, "Map Image Object"),
    (show $ typeOf _OBP, "Object Area Position"),
    (show $ typeOf _ICP, "IM Image Cell Position (C)"),
    (show $ typeOf _FNP, "Font Position"),
    (show $ typeOf _PGP1, "Page Position Format-1 (C)"),
    (show $ typeOf _FNO, "Font Orientation"),
    (show $ typeOf _IPS, "Include Page Segment"),
    (show $ typeOf _IPG, "Include Page"),
    (show $ typeOf _IOB, "Include Object"),
    (show $ typeOf _IPO, "Include Page Overlay"),
    (show $ typeOf _CAT, "Color Attribute Table"),
    (show $ typeOf _MPS, "Map Page Segment"),
    (show $ typeOf _MCF1, "Map Coded Font Format-1 (C)"),
    (show $ typeOf _PTD, "Presentation Text Data Descriptor"),
    (show $ typeOf _PGP, "Page Position"),
    (show $ typeOf _MMO, "Map Medium Overlay"),
    (show $ typeOf _PFC, "Presentation Fidelity Control"),
    (show $ typeOf _IEL, "Index Element"),
    (show $ typeOf _LLE, "Link Logical Element"),
    (show $ typeOf _IRD, "IM Image Raster Data (C)"),
    (show $ typeOf _FNG, "Font Patterns"),
    (show $ typeOf _OCD, "Object Container Data"),
    (show $ typeOf _PTX, "Presentation Text Data"),
    (show $ typeOf _GAD, "Graphics Data"),
    (show $ typeOf _BDA, "Bar Code Data"),
    (show $ typeOf _NOP, "No Operation"),
    (show $ typeOf _IPD, "Image Picture Data"),
    (show $ typeOf _T_CGCSGI, "Coded Graphic Character Set Global ID"),
    (show $ typeOf _T_FQN, "Fully Qualified Name"),
    (show $ typeOf _T_MO, "Mapping Option"),
    (show $ typeOf _T_OCL, "Object Classification"),
    (show $ typeOf _T_MIS, "MO:DCA Interchange Set"),
    (show $ typeOf _T_TO, "Text Orientation (R)"),
    (show $ typeOf _T_FDS, "Font Descriptor Specification"),
    (show $ typeOf _T_FCGCSGI, "Font Coded Graphic Character Set Global Identifier"),
    (show $ typeOf _T_OFSS, "Object Function Set Specification"),
    (show $ typeOf _T_ROT, "Resource Object Type (R)"),
    (show $ typeOf _T_ERLI, "Extended Resource Local ID"),
    (show $ typeOf _T_RLI, "Resource Local ID"),
    (show $ typeOf _T_RSN, "Resource Section Number"),
    (show $ typeOf _T_CR, "Character Rotation"),
    (show $ typeOf _T_LDOPM, "Line Data Object Position Migration (R)"),
    (show $ typeOf _T_OBO, "Object Byte Offset"),
    (show $ typeOf _T_AV, "Attribute Value"),
    (show $ typeOf _T_DP, "Descriptor Position"),
    (show $ typeOf _T_MEC, "Media Eject Control"),
    (show $ typeOf _T_POCP, "Page Overlay Conditional Processing"),
    (show $ typeOf _T_RUA, "Resource Usage Attribute"),
    (show $ typeOf _T_OAMU, "Object Area Measurement Units"),
    (show $ typeOf _T_OAS, "Object Area Size"),
    (show $ typeOf _T_AD, "Area Definition"),
    (show $ typeOf _T_CS, "Color Specification"),
    (show $ typeOf _T_ESI, "Encoding Scheme ID"),
    (show $ typeOf _T_MMPN, "Medium Map Page Number"),
    (show $ typeOf _T_OBE, "Object Byte Extent"),
    (show $ typeOf _T_OSFO, "Object Structured Field Offset"),
    (show $ typeOf _T_OSFE, "Object Structured Field Extent"),
    (show $ typeOf _T_OO, "Object Offset"),
    (show $ typeOf _T_FHSF, "Font Horizontal Scale Factor"),
    (show $ typeOf _T_OCO, "Object Count"),
    (show $ typeOf _T_LDTS, "Local Date and Time Stamp"),
    (show $ typeOf _T_OCH, "Object Checksum (R)"),
    (show $ typeOf _T_T1CRMT, "Type 1 - CRC Resource Management Triplet"),
    (show $ typeOf _T_T2FRMT, "Type 2 - Font Resource Management Triplet"),
    (show $ typeOf _T_OOI, "Object Origin Identifier (R)"),
    (show $ typeOf _T_C, "Comment"),
    (show $ typeOf _T_MOR, "Medium Orientation"),
    (show $ typeOf _T_ROI, "Resource Object Include"),
    (show $ typeOf _T_EF, "Extension Font"),
    (show $ typeOf _T_PSRM, "Presentation Space Reset Mixing"),
    (show $ typeOf _T_PSMR, "Presentation Space Mixing Rules"),
    (show $ typeOf _T_UDTS, "Universal Date and Time Stamp"),
    (show $ typeOf _T_II, "IMM Insertion (R)"),
    (show $ typeOf _T_TS, "Toner Saver"),
    (show $ typeOf _T_CF, "Color Fidelity"),
    (show $ typeOf _T_FF, "Font Fidelity"),
    (show $ typeOf _T_MA, "Metric Adjustment"),
    (show $ typeOf _T_AQ, "Attribute Qualifier"),
    (show $ typeOf _T_PPI, "Page Position Information"),
    (show $ typeOf _T_PV, "Parameter Value"),
    (show $ typeOf _T_PC, "Presentation Control"),
    (show $ typeOf _T_FRMT, "Font Resolution and Metric Technology"),
    (show $ typeOf _T_FO, "Finishing Operation"),
    (show $ typeOf _T_MF, "Media Fidelity"),
    (show $ typeOf _PTX_STC, "Set Text Color"),
    (show $ typeOf _PTX_SIM, "Set Inline Margin"),
    (show $ typeOf _PTX_SIA, "Set Intercharacter Adjustment"),
    (show $ typeOf _PTX_SVI, "Set Variable-Space Character Increment"),
    (show $ typeOf _PTX_AMI, "Absolute Move Inline"),
    (show $ typeOf _PTX_RMI, "Relative Move Inline"),
    (show $ typeOf _PTX_SBI, "Set Baseline Increment"),
    (show $ typeOf _PTX_AMB, "Absolute Move Baseline"),
    (show $ typeOf _PTX_RMB, "Relative Move Baseline"),
    (show $ typeOf _PTX_BLN, "Begin Line Next"),
    (show $ typeOf _PTX_DIR, "Draw I-Axis Rule"),
    (show $ typeOf _PTX_DBR, "Draw B-Axis Rule"),
    (show $ typeOf _PTX_RPS, "Repeat String"),
    (show $ typeOf _PTX_SCFL, "Set Coded Font Local"),
    (show $ typeOf _PTX_BSU, "Begin Suppression"),
    (show $ typeOf _PTX_ESU, "Begin Suppression"),
    (show $ typeOf _PTX_STO, "Set Text Orientation"),
    (show $ typeOf _PTX_NOP, "No Operation"),
    (show $ typeOf _PTX_TRN, "Transparent Data"),
    ("", "(Unknown)")
    ]
